### PR TITLE
fix use of 'csub' on Slurm clusters, don't specify queue

### PR DESCRIPTION
**Pull request by boegel**
WIP because it needs more testing, I started working on this to support automagic checkpointing of Gaussian jobs, but didn't manage to finish it (Gaussian was segfaulting on restart, I think...)

cc @hajgato

### CODE REVIEW

**Comment by wpoely86** [comment]
@smoors has something that seems to work for Gaussian

**Comment by smoors** [comment]
This is what we do for Gaussian 16:
```
module load Gaussian/G16.A.03-intel-2017b
unset LD_PRELOAD
module unload jemalloc/4.5.0-intel-2017b
export G09NOTUNING=1
export GAUSS_SCRDIR=$VSC_SCRATCH/xxx (unique path on a shared filesystem)
```
However it is still not working reliably. I currently advise to use the checkpoint/restart options of Gaussian itself.
http://gaussian.com/faq2/

**Comment by hajgato** [comment]
@wpoely86 @smoors We do have a problem with slurm. See https://sourceforge.net/p/dmtcp/mailman/message/36347021/

**Comment by hajgato** [comment]
@smoors Did you tried `--cleanup_after_restart` option for `csub` ? (and check whether the option does what it should?)

**Comment by smoors** [comment]
@hajgato I did not try that (yet) because the help says `NOT RECOMMENDED` :)

**Comment by boegel** [comment]
@hajgato Only `csub --shared` really makes sense, it should be the default. Not using `--shared` is asking for problems (and more overhead).

**Comment by hajgato** [comment]
@boegel @smoors Gaussian is forking jobs, so if we blindly dmtcp all saved checkpoints, it is possible that an older version of the same subprogram is restarted as well (depends on the calculation, and restarting period, but it will crash Gaussian). At UGent it is not fixed, so we have to use `--cleanup_after_restart`, or we have to implement the solution made by @wpoely86 at VUB. So indeed, at the VUB, this does not make any sense.

Right now we get an error:
```
[25009] mtcp_util.ic:274 mtcp_readfile:
  error 14 reading checkpoint
[25009] mtcp_util.ic:276 mtcp_readfile:
  only read 268210176 bytes instead of 1479553024 from checkpoint file
[25008] mtcp_util.ic:274 mtcp_readfile:
  error 14 reading checkpoint
[25008] mtcp_util.ic:276 mtcp_readfile:
  only read 316911616 bytes instead of 686256128 from checkpoint file
```
And this might be in connection with the `--exit-on-last` flag for the `dmtcp_coordinator`. I will further investigate this issue. (see https://sourceforge.net/p/dmtcp/mailman/message/36511890/)

@smoors can you check (some time) what error do you get if Gaussian fails to restart?

**Comment by boegel** [comment]
@hajgato Is it still relevant to merge this (especially w.r.t. not specifying `-q`)?

**Comment by hajgato** [comment]
@boegel I would still drop the queue. Anyway, I think merging it would not make anything brake.

**Comment by hajgato** [comment]
@boegel ping? Can we merge this one? It will not fix gaussian, but it probably fix simple cases. (right now the `slurm-torque-wrappers/qsub.pl` does not accept `-q` option (or directive).

**Comment by stdweird** [comment]
@hajgato didn't you add support `-q`?

**Comment by hajgato** [comment]
never mind, it does not work. A simple sleep test fails after the 3rd restart (like Gaussian)

**Comment by hajgato** [comment]
@stdweird We hard fail if `-q` is not one of the old queues, where we simply translate it to walltime. (special is also allowed for long queue)

**Comment by boegel** [comment]
@hajgato We should merge this to get rid of the `-q` spec, which is at least a step forward...

**Review by hajgato — APPROVED** [review]

**Pull request merged**
